name = "Cobblemon: Star Academy"
version = "0.1.5.2 noworld"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "666e0a79767a9896616d8fc287020b38687cb6b6c9c499a3c60b29e08211b991"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
