name = "Cobblemon: Star Academy"
version = "0.1.5.2 noworld"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "408696aa820eb1611417c3119591f5f294e28d21bcac8daee845f38570f4b8c1"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
